/** Isolated actual-component browser fixture. Creates/removes a temporary route; no production auth/media. */
import {mkdir,rm,writeFile} from "node:fs/promises";
import {resolve} from "node:path";
const root=resolve(import.meta.dir,".."),out="/tmp/ba4l-gallery-qa",routeDir=resolve(root,"app/gallery-fixture-qa");
await mkdir(out,{recursive:true});await mkdir(routeDir); // Fail rather than overwrite an existing route.
await writeFile(resolve(routeDir,"page.tsx"),`"use client";import {useState} from "react";import Gallery from "../studio/gallery";import "../studio/studio.css";export default function Page(){const [connected,setConnected]=useState(true);return <main className="studio-shell" style={{padding:24}}><button onClick={()=>setConnected(!connected)}>Toggle connection</button><Gallery sessionId="b2222222-2222-4222-8222-222222222222" connected={connected} isOwner/></main>}`);
const userId="a1111111-1111-4111-8111-111111111111",user={id:userId,aud:"authenticated",role:"authenticated",email:"gallery.fixture@example.test",email_confirmed_at:"2026-09-01T00:00:00Z",app_metadata:{},user_metadata:{},identities:[],created_at:"2026-09-01T00:00:00Z"};
const fixture=Bun.serve({port:4335,hostname:"127.0.0.1",fetch(req){return Response.json(new URL(req.url).pathname==="/auth/v1/user"?user:[]);}});
const next=Bun.spawn(["bun","node_modules/next/dist/bin/next","dev","--hostname","127.0.0.1","--port","4336"],{cwd:root,stdout:Bun.file(`${out}/next.log`),stderr:Bun.file(`${out}/next.log`),env:{...process.env,NEXT_PUBLIC_SUPABASE_URL:"http://127.0.0.1:4335",NEXT_PUBLIC_SUPABASE_ANON_KEY:"fixture-key",SUPABASE_URL:"http://127.0.0.1:4335",SUPABASE_SERVICE_ROLE_KEY:"fixture-service",BAFL_ADMIN_EMAILS:user.email}});
let browser:any,checks=0;const origin="http://127.0.0.1:4336";
function check(value:unknown,message:string){if(!value)throw Error(message);checks++;}
try{
 for(let i=0;i<100;i++){try{if((await fetch(origin+"/login")).ok)break;}catch{}await Bun.sleep(500);}
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??`${process.env.HOME}/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs`);
 browser=await chromium.launch({channel:"chrome",headless:true});const context=await browser.newContext();
 const jwt=[Buffer.from('{"alg":"HS256"}').toString("base64url"),Buffer.from(JSON.stringify({sub:userId,exp:Math.floor(Date.now()/1000)+3600,role:"authenticated"})).toString("base64url"),"fixture-signature"].join(".");
 await context.addCookies([{name:"sb-127-auth-token",value:`base64-${Buffer.from(JSON.stringify({access_token:jwt,refresh_token:"fixture-refresh",token_type:"bearer",expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,user})).toString("base64url")}`,domain:"127.0.0.1",path:"/"}]);await context.storageState({path:`${out}/storage.json`});
 let events:any[]=[{id:"c3333333-3333-4333-8333-333333333333",kind:"comment",text:"<img src=x onerror=alert(1)>",author:"Pete",createdAt:new Date().toISOString(),isMine:false}],paused=false,gets=0,failPost=false,terminal=false;
 const posts:any[]=[];let held:any=null,holdNext=false;
 await context.route("**/api/live/v2/sessions/*/gallery",async(route:any)=>{const req=route.request(),method=req.method();if(method==="GET"){gets++;if(holdNext){holdNext=false;held=route;return;}return route.fulfill({status:terminal?403:200,json:terminal?{error:"Access ended"}:{events,paused}});}const body=req.postDataJSON();if(method==="POST"){posts.push(body);if(failPost)return route.fulfill({status:429,json:{error:"Not posted. Please wait before trying again."}});const event={id:crypto.randomUUID(),...body,author:"Doug",createdAt:new Date().toISOString(),isMine:true};events.push(event);return route.fulfill({json:{event}});}if("paused"in body)paused=body.paused;if(body.removeId)events=events.filter(event=>event.id!==body.removeId);return route.fulfill({json:{updated:true}});});
 const page=await context.newPage();page.setDefaultTimeout(15000);const errors:string[]=[];page.on("pageerror",(err:Error)=>errors.push(err.message));await page.goto(origin+"/gallery-fixture-qa");await page.getByText("<img src=x onerror=alert(1)>",{exact:true}).waitFor();check(await page.locator(".gallery-feed img").count()===0,"text rendered inert");
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});check(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),`overflow ${width}`);await page.screenshot({path:`${out}/gallery-${width}.png`,fullPage:true});}
 await page.getByRole("button",{name:"React: Fire"}).click();await page.getByText("Posted to the gallery.",{exact:true}).waitFor();check(posts[0].text==="🔥"&&!Object.hasOwn(posts[0],"author"),"server attributed reaction");
 await page.getByText("Need a good chirp?",{exact:true}).click();await page.getByRole("button",{name:"That pin owes you money.",exact:true}).click();check(await page.getByLabel("Your comment",{exact:true}).inputValue()==="That pin owes you money.","preset is explicit draft");
 await page.getByLabel("Message style").selectOption("coach");await page.getByLabel("Coaching tip",{exact:true}).fill("Keep your finish steady.");failPost=true;await page.getByRole("button",{name:"Send message"}).click();await page.getByText("Not posted. Please wait before trying again.",{exact:true}).waitFor();check(await page.getByLabel("Coaching tip",{exact:true}).inputValue()==="Keep your finish steady.","failure retains draft");failPost=false;await page.getByRole("button",{name:"Send message"}).click();await page.getByText("Keep your finish steady.",{exact:true}).waitFor();check(posts.at(-1).kind==="coach","coaching request kind");
 await page.getByRole("button",{name:"Pause posting",exact:true}).click();await page.getByRole("dialog").waitFor();await page.keyboard.press("Escape");check(!paused,"Escape cancels moderation");await page.getByRole("button",{name:"Pause posting",exact:true}).click();await page.getByRole("button",{name:"Confirm",exact:true}).click();await page.getByText("Gallery posting paused.",{exact:true}).waitFor();check(await page.getByRole("button",{name:"React: Fire"}).isDisabled(),"paused disables posting");await page.getByRole("button",{name:"Resume posting",exact:true}).click();await page.getByRole("button",{name:"Confirm",exact:true}).click();await page.getByText("Gallery posting resumed.",{exact:true}).waitFor();
 holdNext=true;await page.waitForTimeout(3300);check(!!held,"in-flight read prepared");await page.getByRole("button",{name:"Remove message from Pete",exact:true}).click();await page.getByRole("button",{name:"Confirm",exact:true}).click();await page.getByText("Message removed.",{exact:true}).waitFor();await held.fulfill({json:{events:[{id:"c3333333-3333-4333-8333-333333333333",kind:"comment",text:"STALE MESSAGE",author:"Pete",createdAt:new Date().toISOString(),isMine:false}],paused:true}});held=null;await page.waitForTimeout(200);check(await page.getByText("STALE MESSAGE",{exact:true}).count()===0,"late GET cannot undo mutation");
 await page.getByRole("button",{name:"Hide gallery",exact:true}).click();let before=gets;await page.waitForTimeout(3300);check(gets===before,"hidden stops polling");await page.getByRole("button",{name:"Show gallery",exact:true}).click();await page.waitForTimeout(200);await page.getByRole("button",{name:"Toggle connection",exact:true}).click();before=gets;await page.waitForTimeout(3300);check(gets===before,"disconnected stops polling");await page.getByRole("button",{name:"Toggle connection",exact:true}).click();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:`${out}/gallery-posted.png`,fullPage:true});terminal=true;await page.getByText("Access ended",{exact:true}).waitFor({timeout:5000});check(await page.locator(".gallery-feed li").count()===0,"terminal GET clears feed");check(errors.length===0,`JS errors ${errors.join(",")}`);
 console.log(`Gallery QA: ${checks} checks passed. ${out}`);
 if(process.env.GALLERY_KEEP_SERVER==="1")await new Promise<void>(done=>{process.once("SIGTERM",done);process.once("SIGINT",done);});
}finally{await browser?.close();next.kill();fixture.stop();await rm(routeDir,{recursive:true,force:true});}
