/** Isolated actual-component browser fixture. Creates/removes a temporary route; no production auth/media. */
import {mkdir,rm,writeFile} from "node:fs/promises";
import {resolve} from "node:path";
const root=resolve(import.meta.dir,".."),out="/tmp/ba4l-sound-qa",routeDir=resolve(root,"app/sound-fixture-qa");
await mkdir(out,{recursive:true});await mkdir(routeDir); // Fail rather than overwrite an existing route.
await writeFile(resolve(routeDir,"page.tsx"),`"use client";import {useState} from "react";import Soundboard from "../studio/soundboard";import "../studio/studio.css";import "../studio/gallery.css";export default function Page(){const [connected,setConnected]=useState(true);return <main className="studio-shell" style={{padding:24}}><button onClick={()=>setConnected(!connected)}>Toggle connection</button><Soundboard sessionId="b2222222-2222-4222-8222-222222222222" connectionId="d4444444-4444-4444-8444-444444444444" connected={connected} isOwner/></main>}`);
const userId="a1111111-1111-4111-8111-111111111111",user={id:userId,aud:"authenticated",role:"authenticated",email:"gallery.fixture@example.test",email_confirmed_at:"2026-09-01T00:00:00Z",app_metadata:{},user_metadata:{},identities:[],created_at:"2026-09-01T00:00:00Z"};
const fixture=Bun.serve({port:4345,hostname:"127.0.0.1",fetch(req){return Response.json(new URL(req.url).pathname==="/auth/v1/user"?user:[]);}});
const next=Bun.spawn(["bun","node_modules/next/dist/bin/next","dev","--hostname","127.0.0.1","--port","4346"],{cwd:root,stdout:Bun.file(`${out}/next.log`),stderr:Bun.file(`${out}/next.log`),env:{...process.env,NEXT_PUBLIC_SUPABASE_URL:"http://127.0.0.1:4345",NEXT_PUBLIC_SUPABASE_ANON_KEY:"fixture-key",SUPABASE_URL:"http://127.0.0.1:4345",SUPABASE_SERVICE_ROLE_KEY:"fixture-service",BAFL_ADMIN_EMAILS:user.email}});
let browser:any,checks=0;const origin="http://127.0.0.1:4346";
function check(value:unknown,message:string){if(!value)throw Error(message);checks++;}
try{
 for(let i=0;i<100;i++){try{if((await fetch(origin+"/login")).ok)break;}catch{}await Bun.sleep(500);}
 const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??`${process.env.HOME}/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs`);
 browser=await chromium.launch({channel:"chrome",headless:true});const context=await browser.newContext();
 const jwt=[Buffer.from('{"alg":"HS256"}').toString("base64url"),Buffer.from(JSON.stringify({sub:userId,exp:Math.floor(Date.now()/1000)+3600,role:"authenticated"})).toString("base64url"),"fixture-signature"].join(".");
 await context.addCookies([{name:"sb-127-auth-token",value:`base64-${Buffer.from(JSON.stringify({access_token:jwt,refresh_token:"fixture-refresh",token_type:"bearer",expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,user})).toString("base64url")}`,domain:"127.0.0.1",path:"/"}]);await context.storageState({path:`${out}/storage.json`});
 let enabled=true,speaker:string|null=null,clips:any[]=[],events:any[]=[{id:crypto.randomUUID(),soundId:"pickle",author:"Pete",createdAt:new Date().toISOString()}],gets=0,fail=false;
 const posts:any[]=[];
 await context.addInitScript(()=>{const w=window as any;w.audioStarts=0;w.micRequests=0;w.tracks=[];const start=AudioBufferSourceNode.prototype.start;AudioBufferSourceNode.prototype.start=function(...args:any[]){w.audioStarts++;return start.apply(this,args as any);};Object.defineProperty(navigator.mediaDevices,"getUserMedia",{value:async()=>{w.micRequests++;const ctx=new AudioContext(),osc=ctx.createOscillator(),destination=ctx.createMediaStreamDestination();osc.frequency.value=440;osc.connect(destination);osc.start();await ctx.resume();const track=destination.stream.getAudioTracks()[0],stop=track.stop.bind(track);track.stop=()=>{stop();osc.stop();void ctx.close();};w.tracks.push(track);return destination.stream;}});});
 await context.route("**/api/live/v2/sessions/*/soundboard*",async(route:any)=>{const req=route.request();if(req.method()==="GET"){gets++;return route.fulfill({json:{enabled,speakerConnectionId:speaker,clips,events}});}const body=req.postDataJSON();posts.push(body);if(fail)return route.fulfill({status:429,json:{error:"Wait five seconds before another celebration."}});if(body.action==="speaker"){speaker=body.claim?body.connectionId:null;return route.fulfill({json:{claimed:body.claim}});}if(body.action==="enabled")enabled=body.enabled;if(body.action==="save"){const clip={id:crypto.randomUUID(),title:body.title,canRemove:true};clips.push(clip);return route.fulfill({json:{clip}});}if(body.action==="remove")clips=clips.filter(clip=>clip.id!==body.clipId);if(body.action==="play")events.push({id:crypto.randomUUID(),soundId:body.soundId,author:"Doug",createdAt:new Date().toISOString()});return route.fulfill({json:{accepted:true,updated:true,removed:true}});});
 const page=await context.newPage();page.setDefaultTimeout(15000);const errors:string[]=[];page.on("pageerror",(err:Error)=>errors.push(err.message));await page.goto(origin+"/sound-fixture-qa");await page.getByRole("button",{name:"Pickle yodel",exact:true}).waitFor();await page.waitForTimeout(300);
 check(await page.evaluate(()=>(window as any).micRequests===0&&(window as any).audioStarts===0),"no microphone or historical audio on entry");
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});check(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),`overflow ${width}`);await page.screenshot({path:`${out}/sound-${width}.png`,fullPage:true});}
 await page.getByRole("button",{name:"Personal listening",exact:true}).click();await page.waitForTimeout(3300);check(await page.evaluate(()=>(window as any).audioStarts===0),"opting in never replays history");await page.getByRole("button",{name:"Pickle yodel",exact:true}).click();await page.waitForFunction(()=>(window as any).audioStarts===1);check(await page.locator(".sound-celebration").innerText().then((value:string)=>value.includes("Doug")),"fresh attributed audio and visual cue");await page.screenshot({path:`${out}/fresh-cue.png`,fullPage:true});check(await page.locator(".sound-cue-emoji").evaluate((el:HTMLElement)=>getComputedStyle(el).animationName)==="lane-celebrate","fresh emoji motion");await page.emulateMedia({reducedMotion:"reduce"});check(await page.locator(".sound-cue-emoji").evaluate((el:HTMLElement)=>getComputedStyle(el).animationName)==="none","reduced motion stays still");await page.emulateMedia({reducedMotion:"no-preference"});
 let heldAudio:any=null;await context.route("**/sounds/turkey.wav",(route:any)=>{heldAudio=route;});await page.getByRole("button",{name:"Turkey time",exact:true}).click();for(let i=0;i<60&&!heldAudio;i++)await page.waitForTimeout(100);check(!!heldAudio,"delayed audio fetch prepared");const starts=await page.evaluate(()=>(window as any).audioStarts);enabled=false;await page.getByText("The host has muted celebrations for everyone.",{exact:true}).waitFor({timeout:5000});await heldAudio.fulfill({body:await Bun.file(resolve(root,"public/sounds/turkey.wav")).arrayBuffer(),contentType:"audio/wav"});await page.waitForTimeout(300);check(await page.evaluate(()=>(window as any).audioStarts)===starts,"remote mute blocks delayed audio without blocking state polling");await context.unroute("**/sounds/turkey.wav");await page.getByRole("button",{name:"Allow celebrations",exact:true}).click();
 fail=true;await page.getByRole("button",{name:"Turkey time",exact:true}).click();await page.getByRole("alert").filter({hasText:"Wait five seconds"}).waitFor();check(await page.getByText("Celebration sent. Listeners who opted in can hear it.",{exact:true}).count()===0,"failed cue has no success notice");fail=false;
 await page.getByRole("button",{name:"Be the lane speaker",exact:true}).click();await page.waitForTimeout(300);check(speaker==="d4444444-4444-4444-8444-444444444444","speaker explicit claim");await page.getByRole("button",{name:"Hide soundboard",exact:true}).click();await page.waitForTimeout(300);check(speaker===null,"hiding releases speaker");const before=gets;await page.waitForTimeout(3300);check(gets===before,"hidden stops polling");await page.getByRole("button",{name:"Show soundboard",exact:true}).click();
 await page.getByText("Record a team sound",{exact:true}).click();await page.getByRole("button",{name:"Start microphone recording",exact:true}).click();await page.getByRole("button",{name:"Preview recording",exact:true}).waitFor({timeout:12000});check(await page.evaluate(()=>(window as any).tracks.every((track:MediaStreamTrack)=>track.readyState==="ended")),"8 second auto stop ends microphone");check(!posts.some(post=>post.action==="save"),"recording not automatically uploaded");await page.getByRole("button",{name:"Preview recording",exact:true}).click();await page.getByLabel("Sound title",{exact:true}).fill("Team cheer");await page.getByRole("button",{name:"Share with studio",exact:true}).click();await page.getByText("Sound shared with this studio.",{exact:true}).waitFor();const saved=posts.find(post=>post.action==="save"),wav=Buffer.from(saved.audioBase64,"base64");await writeFile(`${out}/synthetic-recording.wav`,wav);check(wav.length<=256044&&wav.toString("ascii",0,4)==="RIFF"&&wav.readUInt32LE(24)===16000&&wav.readUInt16LE(22)===1,"shared WAV bounded mono16k");
 await page.getByRole("button",{name:"Remove sound Team cheer",exact:true}).click();await page.keyboard.press("Escape");check(clips.length===1,"cancel preserves custom sound");await page.getByRole("button",{name:"Remove sound Team cheer",exact:true}).click();await page.getByRole("button",{name:"Remove sound",exact:true}).click();await page.waitForTimeout(300);check(clips.length===0,"confirmed removal");
 await page.getByRole("button",{name:"Start microphone recording",exact:true}).click();await page.waitForTimeout(300);await page.getByRole("button",{name:"Hide soundboard",exact:true}).click();await page.waitForTimeout(300);check(await page.evaluate(()=>(window as any).tracks.every((track:MediaStreamTrack)=>track.readyState==="ended")),"hide aborts in-progress mic");await page.getByRole("button",{name:"Show soundboard",exact:true}).click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:`${out}/sound-final.png`,fullPage:true});check(errors.length===0,`JS errors ${errors.join(",")}`);console.log(`Soundboard QA: ${checks} checks passed. ${out}`);
 if(process.env.SOUND_KEEP_SERVER==="1")await new Promise<void>(done=>{process.once("SIGTERM",done);process.once("SIGINT",done);});
}catch(error){console.error(error);throw error;}finally{await browser?.close();next.kill();fixture.stop();await rm(routeDir,{recursive:true,force:true});}
