import {database} from "../lib/scorebook-server";
import {PUT,GET} from "../app/api/nights/[id]/route";
import {nightSchema} from "../lib/scorebook";
const state=nightSchema.parse({game:1,rolls:[[],[],[],[]],history:[]});
const [created]=await database("scorebooks?select=id,revision",{method:"POST",body:JSON.stringify({state})});
const context={params:Promise.resolve({id:created.id})};
const update=()=>new Request(`https://strike-ceiling-web.vercel.app/api/nights/${created.id}`,{method:"PUT",headers:{Origin:"https://strike-ceiling-web.vercel.app","Content-Type":"application/json"},body:JSON.stringify({state:{...state,rolls:[[9],[],[],[]]},revision:1})});
const responses=await Promise.all([PUT(update(),context),PUT(update(),context)]);
const statuses=responses.map(r=>r.status).sort();
if(JSON.stringify(statuses)!==JSON.stringify([200,409]))throw Error(`Concurrency failed: ${statuses}`);
const read=await GET(new Request("https://strike-ceiling-web.vercel.app"),context);
const saved=await read.json();
if(saved.revision!==2||saved.state.rolls[0][0]!==9)throw Error("Read-back failed");
const invalid=await PUT(new Request(`https://strike-ceiling-web.vercel.app/api/nights/${created.id}`,{method:"PUT",headers:{Origin:"https://example.org","Content-Type":"application/json"},body:JSON.stringify({state,revision:2})}),context);
if(invalid.status!==403)throw Error("Cross-origin edit accepted");
const revisions=await database(`scorebook_revisions?scorebook_id=eq.${created.id}&select=revision`);
if(revisions.length!==2)throw Error("Revision history missing");
const p=Bun.spawn(["supabase","projects","api-keys","--project-ref","aqrigyieuzceksptwfci","-o","json"],{stdout:"pipe",stderr:"pipe"});
const keys=JSON.parse(await new Response(p.stdout).text());await p.exited;
const anon=keys.find((k:{name:string})=>k.name==="anon")?.api_key;if(!anon)throw Error("Anon key unavailable");
const denied=await fetch(`${process.env.SUPABASE_URL}/rest/v1/scorebooks?id=eq.${created.id}`,{headers:{apikey:anon,Authorization:`Bearer ${anon}`}});
if(denied.ok)throw Error("Anonymous database access allowed");
console.log("Verified: concurrent writes 200/409, cross-device read-back, cross-origin denial, revision history, anonymous database access denied. Isolated test board:",created.id);
