"use client";
import {useEffect,useRef,useState} from "react";
import {api} from "./types";
import {base64Audio,decodeBase64,recordSound,SoundPlayer,speakerDeadline} from "./sound-audio";
import "./soundboard.css";
type Clip={id:string;title:string;canRemove?:boolean};type Cue={id:string;soundId:string;author:string;createdAt:string};type State={enabled:boolean;speakerConnectionId:string|null;clips:Clip[];events:Cue[]};
const bundled=[{id:"pickle",title:"Pickle yodel",emoji:"🥒"},{id:"turkey",title:"Turkey time",emoji:"🦃"},{id:"violin",title:"Tiny violin",emoji:"🎻"},{id:"heating",title:"Heating up",emoji:"🔥"}];
export default function Soundboard({sessionId,connectionId,connected,isOwner}:{sessionId:string;connectionId:string;connected:boolean;isOwner:boolean}){
 const [hidden,setHidden]=useState(false),[visible,setVisible]=useState(true),[state,setState]=useState<State|null>(null),[mode,setMode]=useState<"off"|"personal"|"speaker">("off"),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [cue,setCue]=useState<Cue|null>(null),[busy,setBusy]=useState(false),[recording,setRecording]=useState(false),[draft,setDraft]=useState<Uint8Array|null>(null),[title,setTitle]=useState(""),[remove,setRemove]=useState<Clip|null>(null);
 const player=useRef<SoundPlayer|null>(null),request=useRef<AbortController|null>(null),mic=useRef<AbortController|null>(null),stopMic=useRef<(()=>void)|null>(null),epoch=useRef(0),seen=useRef<Set<string>|null>(null),listening=useRef(mode),lease=useRef(false),pending=useRef(false),writes=useRef(0),audioRevision=useRef(0),capturing=useRef(false),leaseUntil=useRef(0),releasePending=useRef<Promise<unknown>>(Promise.resolve()),dialog=useRef<HTMLDialogElement>(null);
 const active=connected&&!!connectionId&&!hidden&&visible;
 const audio=()=>player.current??(player.current=new SoundPlayer());
 const release=()=>{if(lease.current){lease.current=false;leaseUntil.current=0;releasePending.current=api(`/${sessionId}/soundboard`,{method:"POST",body:JSON.stringify({action:"speaker",connectionId,claim:false}),keepalive:true}).catch(()=>{});}return releasePending.current;};
 const silence=()=>{audioRevision.current++;listening.current="off";setMode("off");player.current?.stop();release();};
 useEffect(()=>{const change=()=>setVisible(document.visibilityState==="visible");change();document.addEventListener("visibilitychange",change);return()=>document.removeEventListener("visibilitychange",change);},[]);
 useEffect(()=>{if(remove)dialog.current?.showModal();else dialog.current?.close();},[remove]);
 useEffect(()=>{if(!cue)return;const timer=setTimeout(()=>setCue(null),4000);return()=>clearTimeout(timer);},[cue]);
 useEffect(()=>{
  const current=++epoch.current,abort=new AbortController();request.current=abort;seen.current=null;pending.current=false;setBusy(false);
  let polling=false;const refresh=async()=>{if(polling||pending.current)return;polling=true;const before=writes.current;try{const result=await api<State>(`/${sessionId}/soundboard`,{signal:abort.signal});if(current!==epoch.current||before!==writes.current)return;setState(result);
   if(!result.enabled){audioRevision.current++;player.current?.stop();setCue(null);}
   if(listening.current==="speaker"&&result.speakerConnectionId!==connectionId){silence();setError("This device is no longer the lane speaker. Listening is off.");}
   const fresh=seen.current!==null?result.events.filter(event=>!seen.current!.has(event.id)&&Date.now()-Date.parse(event.createdAt)>=0&&Date.now()-Date.parse(event.createdAt)<=10000).at(-1):null;
   seen.current=new Set(result.events.map(event=>event.id));
   if(fresh&&result.enabled){setCue(fresh);if(listening.current!=="off"&&!capturing.current){const audioVersion=++audioRevision.current;player.current?.stop();void(async()=>{const bundledCue=bundled.some(item=>item.id===fresh.soundId);const bytes=bundledCue?new Uint8Array(await(await fetch(`/sounds/${fresh.soundId}.wav`,{signal:abort.signal})).arrayBuffer()):decodeBase64((await api<{audioBase64:string}>(`/${sessionId}/soundboard?clip=${encodeURIComponent(fresh.soundId)}`,{signal:abort.signal})).audioBase64);if(current===epoch.current&&audioVersion===audioRevision.current&&!capturing.current&&(["personal","speaker"] as string[]).includes(listening.current)&&Date.now()-Date.parse(fresh.createdAt)<=10000)await audio().play(bytes);})().catch(err=>{if(current===epoch.current&&audioVersion===audioRevision.current&&!abort.signal.aborted)setError(err instanceof Error?err.message:"Audio could not play. Try listening again.");});}}
  }catch(err){if(!abort.signal.aborted&&current===epoch.current){audioRevision.current++;player.current?.stop();listening.current="off";setMode("off");void release();setState(null);setCue(null);setDraft(null);setError(err instanceof Error?err.message:"Soundboard could not refresh.");}}finally{polling=false;}};
  if(active)void refresh();const poll=active?setInterval(()=>void refresh(),3000):null;
  const renew=active?setInterval(()=>{if(!lease.current)return;const started=Date.now();void api<{claimed:boolean}>(`/${sessionId}/soundboard`,{method:"POST",body:JSON.stringify({action:"speaker",connectionId,claim:true}),signal:abort.signal}).then(result=>{const confirmedUntil=speakerDeadline(started,Date.now());if(current===epoch.current&&result.claimed&&!confirmedUntil){lease.current=true;silence();setError("Lane speaker confirmation arrived too late. Listening is off.");return;}if(current===epoch.current&&lease.current&&result.claimed)leaseUntil.current=confirmedUntil;if(current===epoch.current&&!result.claimed){silence();setError("The lane speaker lease ended. Listening is off.");}}).catch(()=>{if(current===epoch.current){silence();setError("Could not renew the lane speaker. Listening is off.");}});},15000):null;
  const deadline=active?setInterval(()=>{if(lease.current&&Date.now()>=leaseUntil.current){silence();setError("Lane speaker confirmation expired. Listening is off.");}},1000):null;
  return()=>{epoch.current++;audioRevision.current++;capturing.current=false;abort.abort();if(poll)clearInterval(poll);if(renew)clearInterval(renew);if(deadline)clearInterval(deadline);mic.current?.abort();stopMic.current=null;player.current?.close();silence();setRecording(false);setDraft(null);setCue(null);setRemove(null);};
 },[active,sessionId,connectionId]);
 async function action(body:object){const current=epoch.current;writes.current++;const result=await api<any>(`/${sessionId}/soundboard`,{method:"POST",body:JSON.stringify(body),signal:request.current?.signal});if(current!==epoch.current)throw new DOMException("Cancelled","AbortError");writes.current++;return result;}
 async function run(work:()=>Promise<void>){if(pending.current||!active)return;pending.current=true;setBusy(true);setError("");setNotice("");const current=epoch.current;try{await work();}catch(err){if(current===epoch.current)setError(err instanceof Error?err.message:"The soundboard action failed. Try again.");}finally{if(current===epoch.current){pending.current=false;setBusy(false);}}}
 async function choose(next:"off"|"personal"|"speaker"){
  if(next===listening.current)return;const current=epoch.current;silence();seen.current=null;if(next==="off")return;const unlocked=audio().unlock();await releasePending.current;await unlocked;if(current!==epoch.current)return;if(next==="speaker"){const started=Date.now();const result=await action({action:"speaker",connectionId,claim:true});if(current!==epoch.current){if(result.claimed)void action({action:"speaker",connectionId,claim:false}).catch(()=>{});return;}if(!result.claimed)throw Error("Another device is the lane speaker. Use personal listening with headphones, or wait for its lease to end.");lease.current=true;leaseUntil.current=speakerDeadline(started,Date.now());if(!leaseUntil.current){silence();await releasePending.current;throw Error("Lane speaker confirmation arrived too late. Try again.");}}
  if(current===epoch.current){listening.current=next;setMode(next);}
 }
 async function record(){if(recording||!active)return;audioRevision.current++;player.current?.stop();capturing.current=true;const current=epoch.current,abort=new AbortController();mic.current=abort;setError("");setDraft(null);setRecording(true);try{const recorder=await recordSound(abort.signal);if(current!==epoch.current){abort.abort();return;}stopMic.current=recorder.stop;const bytes=await recorder.finished;if(current===epoch.current){capturing.current=false;setDraft(bytes);setRecording(false);stopMic.current=null;}}catch(err){if(current===epoch.current){capturing.current=false;setRecording(false);setError(err instanceof Error?err.message:"Microphone could not start.");}}}
 return <section className="soundboard" aria-label="League soundboard"><header><div><h2>Make some noise</h2><p>Manual celebrations for the lane. Sound starts off.</p></div><button aria-expanded={!hidden} onClick={()=>setHidden(!hidden)}>{hidden?"Show soundboard":"Hide soundboard"}</button></header>{hidden?<p>Hidden on this device. Listening and recording are off.</p>:<>
 {!connected&&<p>Join the studio to use the soundboard.</p>}{error&&!remove&&<p role="alert" className="studio-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <fieldset disabled={!active||busy}><legend>Listening on this device</legend><div className="sound-listening">{([['off','Off'],['personal','Personal listening'],['speaker','Be the lane speaker']]as const).map(([value,label])=><button key={value} aria-pressed={mode===value} onClick={()=>void run(()=>choose(value))}>{label}</button>)}</div><p className="studio-caption">Use headphones for personal listening. Only one device holds the lane speaker role. Turning sound on never replays old celebrations.</p></fieldset>
 {cue&&<div key={cue.id} className="sound-celebration" role="status"><strong>{cue.author}</strong><span className="sound-cue-label"><span className="sound-cue-emoji" aria-hidden="true">{bundled.find(item=>item.id===cue.soundId)?.emoji??"🎵"}</span> {bundled.find(item=>item.id===cue.soundId)?.title??state?.clips.find(item=>item.id===cue.soundId)?.title??"Custom celebration"}</span></div>}
 {state&&!state.enabled&&<p className="studio-notice">The host has muted celebrations for everyone.</p>}
 <div className="sound-cues">{bundled.map(item=><button key={item.id} disabled={!active||busy||!state?.enabled} onClick={()=>void run(async()=>{await action({action:"play",soundId:item.id,connectionId});setNotice("Celebration sent. Listeners who opted in can hear it.");})}><span aria-hidden="true">{item.emoji}</span>{item.title}</button>)}</div>
 {isOwner&&<button disabled={!active||busy||!state} onClick={()=>void run(async()=>{const enabled=!state!.enabled;await action({action:"enabled",enabled});setState(old=>old?{...old,enabled}:old);if(!enabled){audioRevision.current++;player.current?.stop();setCue(null);}})}>{state?.enabled?"Mute celebrations for everyone":"Allow celebrations"}</button>}
 <details className="sound-custom"><summary>Record a team sound</summary><p>Up to 8 seconds, microphone only. Preview here, then choose Share. Recording is never added to the live camera audio.</p><button disabled={!active||busy} onClick={()=>recording?(stopMic.current?stopMic.current():mic.current?.abort()):void record()}>{recording?"Stop recording":"Start microphone recording"}</button>{recording&&<p role="status">Recording. Stops automatically at 8 seconds.</p>}{draft&&<div className="sound-draft"><button disabled={!active||busy} onClick={()=>void run(async()=>{audioRevision.current++;await audio().play(draft);})}>Preview recording</button><label>Sound title<input maxLength={40} value={title} onChange={event=>setTitle(event.target.value)}/></label><button className="studio-primary" disabled={!active||busy||!title.trim()} onClick={()=>void run(async()=>{const result=await action({action:"save",title:title.trim(),audioBase64:base64Audio(draft)});if(!result.clip)throw Error("The server did not confirm this sound was saved.");setState(old=>old?{...old,clips:[...old.clips.filter(item=>item.id!==result.clip.id),{...result.clip,canRemove:true}]}:old);setDraft(null);setTitle("");setNotice("Sound shared with this studio.");})}>Share with studio</button><button onClick={()=>{player.current?.stop();setDraft(null);}}>Discard recording</button></div>}</details>
 {!!state?.clips.length&&<ul className="sound-clips">{state.clips.map(clip=><li key={clip.id}><button disabled={!active||busy||!state.enabled} onClick={()=>void run(async()=>{await action({action:"play",soundId:clip.id,connectionId});setNotice("Celebration sent.");})}>{clip.title}</button>{(isOwner||clip.canRemove)&&<button disabled={!active||busy} onClick={()=>setRemove(clip)} aria-label={`Remove sound ${clip.title}`}>Remove</button>}</li>)}</ul>}
 </>}
 <dialog ref={dialog} className="gallery-dialog" aria-labelledby="sound-remove-title" onCancel={()=>setRemove(null)} onClose={()=>setRemove(null)}><h2 id="sound-remove-title">Remove this sound?</h2><p>This removes “{remove?.title}” from the studio for everyone.</p>{remove&&error&&<p role="alert">{error}</p>}<div><button autoFocus onClick={()=>setRemove(null)}>Cancel</button><button disabled={busy} onClick={()=>remove&&void run(async()=>{const id=remove.id;await action({action:"remove",clipId:id});setState(old=>old?{...old,clips:old.clips.filter(clip=>clip.id!==id)}:old);setRemove(null);})}>Remove sound</button></div></dialog>
 </section>;
}
